
nginx:
  restart: always
  build: ./nginx/
  ports: 
    - "80:80"
  volumes:
     - /www/static
    - /home/deploy/deploy/log/nginx:/var/log/nginx
  volumes_from:
    - web
  links:
    - web:web

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

web:
  restart: always
  dockerfile: Dockerfile-production
  build: .
  expose:
    - "8000"
  env_file: env.secret
  links:
    - redis:redis
    - celery:celery
  command: /usr/src/app/uwsgi/init.sh

celery:
  build: .
  dockerfile: Dockerfile-production
  command: celery -A common worker -l info
  volumes:
    - .:/usr/src/app
  env_file: env.secret
  links:
    - redis:redis
